# Generated by Django 2.2.19 on 2022-07-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220731_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_events', to='telegram.TelegramUser', verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.TelegramUser'),
        ),
    ]
