# Generated by Django 2.2.19 on 2022-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220812_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='events/', verbose_name='Event photo'),
        ),
    ]
