# Generated by Django 2.2.19 on 2022-08-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220803_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_events', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
