# Generated by Django 2.2.19 on 2022-08-04 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20220804_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarked_events', to=settings.AUTH_USER_MODEL, verbose_name='bookmarks'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
