# Generated by Django 2.2.19 on 2022-08-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_auto_20220803_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_id',
            new_name='id',
        ),
    ]
